apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: cdc-demo
    component: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cdc-demo
        component: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: debezium
            - name: MYSQL_USER
              value: mysqluser
            - name: MYSQL_PASSWORD
              value: mysqlpw
          image: debezium/example-mysql:0.8
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
            - containerPort: 33060
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume-1
      volumes:
        - emptyDir: {}
          name: mysql-volume-1
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: cdc-demo
    component: mysql
spec:
  type: ClusterIP
  ports:
   - name: mysql
     port: 3306
   - name: mysql0
     port: 33060
  selector:
    app: cdc-demo
    component: mysql