apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service
  labels:
    app: cdc-demo
    component: service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cdc-demo
        component: service
    spec:
      containers:
        - image: scholzj/devconf2019-cdc-service
          imagePullPolicy: IfNotPresent
          name: service
          ports:
            - containerPort: 8080
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: cdc-demo
    component: service
spec:
  type: ClusterIP
  ports:
   - name: http
     port: 8080
  selector:
    app: cdc-demo
    component: service
---

apiVersion: v1
kind: Route
metadata:
  name: service
  labels:
    app: cdc-demo
    component: service
spec:
  to:
    kind: Service
    name: service