apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cdc-demo
    component: watcher
  name: cdc-demo-watcher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cdc-demo
        component: watcher
    spec:
      containers:
      - name: cdc-demo-watcher
        image: scholzj/devconf2019-cdc-watcher:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: dbserver1.inventory.customers
          - name: GROUP_ID
            value: consumer-demo-watcher