apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consumer-demo
    component: shipping
  name: consumer-demo-shipping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-demo
        component: shipping
    spec:
      containers:
      - name: consumer-demo-shipping
        image: scholzj/devconf2019-consumer-shipping:latest
        imagePullPolicy: Always
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: consumer-demo
          - name: GROUP_ID
            value: consumer-demo-shipping
        ports:
          - containerPort: 8080