apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: consumer-demo
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 3600000
    segment.bytes: 107374182